### ISSUE TITLE
production.ERROR: exception 'Adldap\Exceptions\Auth\BindException' with message 'Can't contact LDAP server' in /web/vendor/adldap2/adldap2/src/Auth/Guard.php:86

### ISSUE THREAD

**Issue by osmelpv** [Adldap2/Adldap2-Laravel#124]
[2016-06-27 07:30:15] production.ERROR: exception 'Adldap\Exceptions\Auth\BindException' with message 'Can't contact LDAP server' in /web/vendor/adldap2/adldap2/src/Auth/Guard.php:86
Stack trace:
```
#0 /web/vendor/adldap2/adldap2/src/Auth/Guard.php(102): Adldap\Auth\Guard->bind('user', 'pass', '', '@mydom.local')
#1 /web/vendor/adldap2/adldap2/src/Connections/Provider.php(191): Adldap\Auth\Guard->bindAsAdministrator()
#2 /web/vendor/adldap2/adldap2-laravel/src/AdldapServiceProvider.php(93): Adldap\Connections\Provider->connect()
#3 /web/vendor/laravel/framework/src/Illuminate/Support/Collection.php(146): Adldap\Laravel\AdldapServiceProvider->Adldap\Laravel\{closure}(Array, 'default')
#4 /web/vendor/adldap2/adldap2-laravel/src/AdldapServiceProvider.php(98): Illuminate\Support\Collection->each(Object(Closure))
#5 /web/vendor/adldap2/adldap2-laravel/src/AdldapServiceProvider.php(50): Adldap\Laravel\AdldapServiceProvider->addProviders(Object(Adldap\Adldap), Array)
#6 /web/vendor/laravel/framework/src/Illuminate/Container/Container.php(731): Adldap\Laravel\AdldapServiceProvider->Adldap\Laravel\{closure}(Object(Illuminate\Foundation\Application), Array)
#7 /web/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\Container\Container->build(Object(Closure), Array)
#8 /web/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(697): Illuminate\Container\Container->make('adldap', Array)
#9 /web/vendor/laravel/framework/src/Illuminate/Container/Container.php(1174): Illuminate\Foundation\Application->make('adldap')
#10 /web/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(151): Illuminate\Container\Container->offsetGet('adldap')
#11 /web/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(120): Illuminate\Support\Facades\Facade::resolveFacadeInstance('adldap')
#12 /web/vendor/adldap2/adldap2-laravel/src/Traits/ImportsUsers.php(235): Illuminate\Support\Facades\Facade::getFacadeRoot()
#13 /web/vendor/adldap2/adldap2-laravel/src/Traits/ImportsUsers.php(223): Adldap\Laravel\AdldapAuthUserProvider->getAdldap()
#14 /web/vendor/adldap2/adldap2-laravel/src/Traits/ImportsUsers.php(304): Adldap\Laravel\AdldapAuthUserProvider->getSchema()
```

i am getting in my log many errors like this in a short time. Do you know what is appending?

**Comment by stevebauman** [comment]
Hi @osmelpv, it looks like your LDAP server isn't available. Are you sure you've entered the correct information in your `config/adldap.php` file?

**Comment by osmelpv** [comment]
yes, is correct, and i got this error many time in only 20, 30 or 40 seconds and after that no more in the day, maybe it is what you say, in this exactly moment Adldap2-Laravel lost the connection. Thank you.

**Comment by stevebauman** [comment]
Strange, but you're right, this was most likely just connection loss to the server.

Keep me posted if you continue to encounter more connection errors!
