### ISSUE TITLE
Authentication not working

### ISSUE THREAD

**Issue by c0py** [Adldap2/Adldap2-Laravel#470]
- Laravel Version: 5.5.33
- Adldap2-Laravel Version: 3.0.9
- PHP Version: 7.1.7
- LDAP Type: Active Directory

### Description:

When trying to authenticate I get the following error which causes authentication to break:

```
[2018-01-30 16:13:17] local.ERROR: Call to undefined method Adldap\Laravel\Auth\DatabaseUserProvider::getModel() {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to undefined method Adldap\\Laravel\\Auth\\DatabaseUserProvider::getModel() at C:\\inetpub\\wwwroot\\ServerDB\\vendor\\tymon\\jwt-auth\\src\\JWTGuard.php:77)
[stacktrace]
#0 C:\\inetpub\\wwwroot\\ServerDB\\vendor\\laravel\\framework\\src\\Illuminate\\Auth\\GuardHelpers.php(50): Tymon\\JWTAuth\\JWTGuard->user()
#1 C:\\inetpub\\wwwroot\\ServerDB\\vendor\\laravel\\framework\\src\\Illuminate\\Auth\\Middleware\\Authenticate.php(61): Tymon\\JWTAuth\\JWTGuard->check()
#2 C:\\inetpub\\wwwroot\\ServerDB\\vendor\\laravel\\framework\\src\\Illuminate\\Auth\\Middleware\\Authenticate.php(41): Illuminate\\Auth\\Middleware\\Authenticate->authenticate(Array)
#3 C:\\inetpub\\wwwroot\\ServerDB\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(149): Illuminate\\Auth\\Middleware\\Authenticate->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure), 'api')
#4 C:\\inetpub\\wwwroot\\ServerDB\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))
#5 C:\\inetpub\\wwwroot\\ServerDB\\vendor\\dingo\\api\\src\\Http\\Middleware\\PrepareController.php(45): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Dingo\\Api\\Http\\Request))
#6 C:\\inetpub\\wwwroot\\ServerDB\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(149): Dingo\\Api\\Http\\Middleware\\PrepareController->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))
#7 C:\\inetpub\\wwwroot\\ServerDB\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))
#8 C:\\inetpub\\wwwroot\\ServerDB\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Dingo\\Api\\Http\\Request))
#9 C:\\inetpub\\wwwroot\\ServerDB\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(660): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#10 C:\\inetpub\\wwwroot\\ServerDB\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(635): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Dingo\\Api\\Http\\Request))
#11 C:\\inetpub\\wwwroot\\ServerDB\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(601): Illuminate\\Routing\\Router->runRoute(Object(Dingo\\Api\\Http\\Request), Object(Illuminate\\Routing\\Route))
#12 C:\\inetpub\\wwwroot\\ServerDB\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(590): Illuminate\\Routing\\Router->dispatchToRoute(Object(Dingo\\Api\\Http\\Request))
#13 C:\\inetpub\\wwwroot\\ServerDB\\vendor\\dingo\\api\\src\\Routing\\Adapter\\Laravel.php(81): Illuminate\\Routing\\Router->dispatch(Object(Dingo\\Api\\Http\\Request))
#14 C:\\inetpub\\wwwroot\\ServerDB\\vendor\\dingo\\api\\src\\Routing\\Router.php(512): Dingo\\Api\\Routing\\Adapter\\Laravel->dispatch(Object(Dingo\\Api\\Http\\Request), 'v1')
#15 C:\\inetpub\\wwwroot\\ServerDB\\vendor\\dingo\\api\\src\\Http\\Middleware\\Request.php(126): Dingo\\Api\\Routing\\Router->dispatch(Object(Dingo\\Api\\Http\\Request))
#16 C:\\inetpub\\wwwroot\\ServerDB\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(114): Dingo\\Api\\Http\\Middleware\\Request->Dingo\\Api\\Http\\Middleware\\{closure}(Object(Dingo\\Api\\Http\\Request))
#17 C:\\inetpub\\wwwroot\\ServerDB\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(30): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))
#18 C:\\inetpub\\wwwroot\\ServerDB\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))
#19 C:\\inetpub\\wwwroot\\ServerDB\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(30): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))
#20 C:\\inetpub\\wwwroot\\ServerDB\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))
#21 C:\\inetpub\\wwwroot\\ServerDB\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))
#22 C:\\inetpub\\wwwroot\\ServerDB\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))
#23 C:\\inetpub\\wwwroot\\ServerDB\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode.php(46): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))
#24 C:\\inetpub\\wwwroot\\ServerDB\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))
#25 C:\\inetpub\\wwwroot\\ServerDB\\vendor\\barryvdh\\laravel-cors\\src\\HandlePreflight.php(34): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))
#26 C:\\inetpub\\wwwroot\\ServerDB\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(149): Barryvdh\\Cors\\HandlePreflight->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))
#27 C:\\inetpub\\wwwroot\\ServerDB\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(102): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))
#28 C:\\inetpub\\wwwroot\\ServerDB\\vendor\\dingo\\api\\src\\Http\\Middleware\\Request.php(127): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#29 C:\\inetpub\\wwwroot\\ServerDB\\vendor\\dingo\\api\\src\\Http\\Middleware\\Request.php(103): Dingo\\Api\\Http\\Middleware\\Request->sendRequestThroughRouter(Object(Dingo\\Api\\Http\\Request))
#30 C:\\inetpub\\wwwroot\\ServerDB\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(149): Dingo\\Api\\Http\\Middleware\\Request->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))
#31 C:\\inetpub\\wwwroot\\ServerDB\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#32 C:\\inetpub\\wwwroot\\ServerDB\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#33 C:\\inetpub\\wwwroot\\ServerDB\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#34 C:\\inetpub\\wwwroot\\ServerDB\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#35 C:\\inetpub\\wwwroot\\ServerDB\\public\\index.php(53): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#36 {main}
"} 
```

Basically getModel() method does not exist in Adldap\Laravel\Auth\DatabaseUserProvider.php as reported in issue #444

### Steps To Reproduce:

Try to authenticate using Adldap2-laravel 3.*

**Comment by stevebauman** [comment]
Hi @c0py, please update to `v4.0`. This will resolve your issue.

We also don't support using other authentication types with Adldap2 (such as JWTAuth).

**Comment by stevebauman** [comment]
To elaborate on support, JWTAuth should update their library to retrieve the users current model using a concrete implementation of the `Illuminate\Contracts\Auth\UserProvider`.

Notice how the JWT library is calling the method `getModel()` from the current authentication provider, yet this method isn't implemented in the interface, so this exception will occur on any other provider besides the built in `EloquentUserProvider`:

https://github.com/laravel/framework/blob/5.5/src/Illuminate/Contracts/Auth/UserProvider.php

Please create an issue on their package with this detail for them to resolve.

**Comment by stevebauman** [comment]
Note: This was added in the `develop` branch of JWTAuth:

https://github.com/tymondesigns/jwt-auth/blob/develop/src/JWTGuard.php#L390-L404

Which validates this method now, however it is not contained in the `1.0.0-rc1` release.

**Comment by c0py** [comment]
Perfect, thanks :)

**Comment by stevebauman** [comment]
No problem! :)
