### ISSUE TITLE
The default login controller

### ISSUE THREAD

**Issue by aloooirule** [Adldap2/Adldap2-Laravel#717]
- Laravel Version: 5.4 upgraded to 5.5
- Adldap2-Laravel Version: 6.0.4
- PHP Version: 7.1.25
- LDAP Type: 

### Description:

Thanks for the great package, I have managed to connect and authenticate, the issue now I can't use the middle ware or sync the user to my database so I can use the roles from the database. I read here that the login controller no need to be edited but I can't authenticate without adding `Adldap::auth()->attempt($request->username, $request->password`

**Comment by stevebauman** [comment]
Hi @aloooirule,

> I have managed to connect and authenticate, the issue now I can't use the middle ware or sync the user to my database so I can use the roles from the database.

How do you know if you can connect and authenticate fine? I'll need a lot more information to help you out:

- What LDAP server are you using (ActiveDirectory / OpenLDAP / SunDirectory etc.)?
- Did you follow the [setup guide](https://adldap2.github.io/Adldap2-Laravel/#/auth/setup)?
- Have you checked your `storage/logs` directory to see where it's failing?

**Comment by aloooirule** [comment]
Hi @stevebauman thanks for your reply, I am using ActiveDirectory. and my Laravel was 5.4 and upgraded it to 5.5. And yes I have followed the setup guide.

To explain the issue more, when I use the code in my login controller I can see in the log that it is passed the authentication.

LoginController.php
`    public function login(Request $request)
    {
        if (Adldap::auth()->attempt($request->username, $request->password)) {
    
            // Returns \App\User model configured in `config/auth.php`.
            $user = Auth::user();
           
            return redirect()->to('/')
                ->withMessage('Logged in!');
        }
            return redirect()->to('login')
            ->withMessage('wrong password please!');`

Mylog


`[2019-04-18 06:55:52] local.INFO: LDAP (ldap://192.168.17.4:389) - Connection:  - Operation: Adldap\Auth\Events\Binding - Username: Administrator@####  
[2019-04-18 06:55:52] local.INFO: LDAP (ldap://192.168.17.4:389) - Connection:  - Operation: Adldap\Auth\Events\Bound - Username: Administrator@####  
[2019-04-18 06:55:52] local.INFO: LDAP (ldap://192.168.17.4:389) - Connection:  - Operation: Adldap\Auth\Events\Attempting - Username: Administrator  
[2019-04-18 06:55:52] local.INFO: LDAP (ldap://192.168.17.4:389) - Connection:  - Operation: Adldap\Auth\Events\Binding - Username: Administrator  
[2019-04-18 06:55:52] local.INFO: LDAP (ldap://192.168.17.4:389) - Connection:  - Operation: Adldap\Auth\Events\Bound - Username: Administrator  
[2019-04-18 06:55:52] local.INFO: LDAP (ldap://192.168.17.4:389) - Connection:  - Operation: Adldap\Auth\Events\Passed - Username: Administrator  
[2019-04-18 06:55:52] local.INFO: LDAP (ldap://192.168.17.4:389) - Connection:  - Operation: Adldap\Auth\Events\Binding - Username: Administrator@####  
[2019-04-18 06:55:52] local.INFO: LDAP (ldap://192.168.17.4:389) - Connection:  - Operation: Adldap\Auth\Events\Bound - Username: Administrator@####  
`
But when I remove that code in my controller, I just get these two lines of log below. I believe it passed empty values
`[2019-04-18 06:55:52] local.INFO: LDAP (ldap://192.168.17.4:389) - Connection:  - Operation: Adldap\Auth\Events\Binding - Username: Administrator@####  
[2019-04-18 06:55:52] local.INFO: LDAP (ldap://192.168.17.4:389) - Connection:  - Operation: Adldap\Auth\Events\Bound - Username: Administrator@####  `


My ldap_auth.php

`
<?php

return [


    'connection' => env('LDAP_CONNECTION', 'default'),
    'provider' => Adldap\Laravel\Auth\DatabaseUserProvider::class,
    'resolver' => Adldap\Laravel\Auth\Resolver::class,
    'importer' => Adldap\Laravel\Auth\Importer::class,
    'model' => App\User::class,
    'rules' => [


    ],
    'scopes' => [
    ],

    'identifiers' => [

        'ldap' => [
            
            'locate_users_by' => 'userprincipalname',
            'bind_users_by' => 'distinguishedname',

        ],

        'database' => [

            'guid_column' => 'objectguid',
            'username_column' => 'username',

        ],

        

        'windows' => [

            'locate_users_by' => 'samaccountname',
            'server_key' => 'AUTH_USER',

        ],

    ],

    'passwords' => [

        'sync' => env('LDAP_PASSWORD_SYNC', true),
        'column' => 'password',

    ],

    'login_fallback' => env('LDAP_LOGIN_FALLBACK', true),
    'sync_attributes' => [

        'username' => 'userprincipalname',
        'guid_column' => 'objectguid',
        'column' => 'password',
    ],

    'logging' => [

        'enabled' => env('LDAP_LOGGING', true),

        'events' => [

            \Adldap\Laravel\Events\Importing::class => \Adldap\Laravel\Listeners\LogImport::class,
            \Adldap\Laravel\Events\Synchronized::class => \Adldap\Laravel\Listeners\LogSynchronized::class,
            \Adldap\Laravel\Events\Synchronizing::class => \Adldap\Laravel\Listeners\LogSynchronizing::class,
            \Adldap\Laravel\Events\Authenticated::class => \Adldap\Laravel\Listeners\LogAuthenticated::class,
            \Adldap\Laravel\Events\Authenticating::class => \Adldap\Laravel\Listeners\LogAuthentication::class,
            \Adldap\Laravel\Events\AuthenticationFailed::class => \Adldap\Laravel\Listeners\LogAuthenticationFailure::class,
            \Adldap\Laravel\Events\AuthenticationRejected::class => \Adldap\Laravel\Listeners\LogAuthenticationRejection::class,
            \Adldap\Laravel\Events\AuthenticationSuccessful::class => \Adldap\Laravel\Listeners\LogAuthenticationSuccess::class,
            \Adldap\Laravel\Events\DiscoveredWithCredentials::class => \Adldap\Laravel\Listeners\LogDiscovery::class,
            \Adldap\Laravel\Events\AuthenticatedWithWindows::class => \Adldap\Laravel\Listeners\LogWindowsAuth::class,
            \Adldap\Laravel\Events\AuthenticatedModelTrashed::class => \Adldap\Laravel\Listeners\LogTrashedModel::class,

        ],
    ],

];

`


Another thing that worth to mention, when I try to `php artisan adldap:import ` it shows no users found with the error below in my log

`
[2019-04-18 07:01:15] local.INFO: LDAP (ldap://192.168.17.4:389) - Connection:  - Operation: Adldap\Auth\Events\Binding - Username: Administrator@rcsi.local  
[2019-04-18 07:01:15] local.INFO: LDAP (ldap://192.168.17.4:389) - Connection:  - Operation: Adldap\Auth\Events\Bound - Username: Administrator@rcsi.local  
[2019-04-18 07:01:15] local.ERROR: There were no users found to import. {"exception":"[object] (RuntimeException(code: 0): There were no users found to import. at C:\\xampp\\htdocs\\RssPortal45\\RssPortal\\vendor\\adldap2\\adldap2-laravel\\src\\Commands\\Console\\Import.php:55)
[stacktrace]
#0 [internal function]: Adldap\\Laravel\\Commands\\Console\\Import->handle()
#1 C:\\xampp\\htdocs\\RssPortal45\\RssPortal\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(29): call_user_func_array(Array, Array)
#2 C:\\xampp\\htdocs\\RssPortal45\\RssPortal\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#3 C:\\xampp\\htdocs\\RssPortal45\\RssPortal\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#4 C:\\xampp\\htdocs\\RssPortal45\\RssPortal\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(549): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#5 C:\\xampp\\htdocs\\RssPortal45\\RssPortal\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(180): Illuminate\\Container\\Container->call(Array)
#6 C:\\xampp\\htdocs\\RssPortal45\\RssPortal\\vendor\\symfony\\console\\Command\\Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#7 C:\\xampp\\htdocs\\RssPortal45\\RssPortal\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(167): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#8 C:\\xampp\\htdocs\\RssPortal45\\RssPortal\\vendor\\symfony\\console\\Application.php(960): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#9 C:\\xampp\\htdocs\\RssPortal45\\RssPortal\\vendor\\symfony\\console\\Application.php(255): Symfony\\Component\\Console\\Application->doRunCommand(Object(Adldap\\Laravel\\Commands\\Console\\Import), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#10 C:\\xampp\\htdocs\\RssPortal45\\RssPortal\\vendor\\symfony\\console\\Application.php(148): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#11 C:\\xampp\\htdocs\\RssPortal45\\RssPortal\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Application.php(82): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#12 C:\\xampp\\htdocs\\RssPortal45\\RssPortal\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(125): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#13 C:\\xampp\\htdocs\\RssPortal45\\RssPortal\\artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#14 {main}
"} 

`
