### ISSUE TITLE
ERROR: Class config does not exist

### ISSUE THREAD

**Issue by warlord0** [Adldap2/Adldap2-Laravel#772]
- Laravel Version: 5.8.32
- Adldap2-Laravel Version: 6.0.7
- PHP Version: 7.1.31
- LDAP Type: ActiveDirectory

### Description:

PHPUnit fails when running more than one test when `LDAP_LOGGING=true`

### Steps To Reproduce:

Edit `.env` and set `LDAP_LOGGING=false`

Run a unit test (that contains several test functions) which usually succeeds eg.

```console
> $ ./vendor/phpunit/phpunit/phpunit -v --coverage-html ./tests/codeCoverage tests/Unit/FOI/FOIDelegatedQuestionsTest.php                                    

PHPUnit 7.5.14 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.1.31-1+0~20190807.22+debian9~1.gbpf402ed with Xdebug 2.7.2
Configuration: /home/warlord/itsm/phpunit.xml

......                                                              6 / 6 (100%)

Time: 48.22 seconds, Memory: 134.00 MB

OK (6 tests, 10 assertions)

Generating code coverage report in HTML format ... done
```

Now edit `.env` and set `LDAP_LOGGING=true`

The rerun the same test and see the following in the `laravel.log` when the second test is run. The first test function called succeeds.

If I use `--filter` to run only one test function at a time each test will succeed. It only fails if I allow it to run all tests, or multiple tests in the file.

```text
[2019-08-20 09:42:11] testing.ERROR: Class config does not exist {"userId":9696,"exception":"[object] (ReflectionException(code: -1): Class config does not exist at /home/warlord/itsm/vendor/laravel/framework/src/Illuminate/Container/Container.php:790)
[stacktrace]
#0 /home/warlord/itsm/vendor/laravel/framework/src/Illuminate/Container/Container.php(790): ReflectionClass->__construct('config')
#1 /home/warlord/itsm/vendor/laravel/framework/src/Illuminate/Container/Container.php(667): Illuminate\\Container\\Container->build('config')
#2 /home/warlord/itsm/vendor/laravel/framework/src/Illuminate/Container/Container.php(615): Illuminate\\Container\\Container->resolve('config', Array)
#3 /home/warlord/itsm/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(767): Illuminate\\Container\\Container->make('config', Array)
#4 /home/warlord/itsm/vendor/laravel/framework/src/Illuminate/Container/Container.php(1229): Illuminate\\Foundation\\Application->make('config')
#5 /home/warlord/itsm/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(417): Illuminate\\Container\\Container->offsetGet('config')
#6 /home/warlord/itsm/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(90): Illuminate\\Log\\LogManager->getDefaultDriver()
#7 /home/warlord/itsm/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(544): Illuminate\\Log\\LogManager->driver()
#8 /home/warlord/itsm/vendor/adldap2/adldap2/src/Log/EventLogger.php(72): Illuminate\\Log\\LogManager->info('LDAP (ldap://DC...')
#9 /home/warlord/itsm/vendor/adldap2/adldap2/src/Log/EventLogger.php(39): Adldap\\Log\\EventLogger->auth(Object(Adldap\\Auth\\Events\\Binding))
#10 /home/warlord/itsm/vendor/adldap2/adldap2/src/Adldap.php(181): Adldap\\Log\\EventLogger->log(Object(Adldap\\Auth\\Events\\Binding))
#11 /home/warlord/itsm/vendor/adldap2/adldap2/src/Events/Dispatcher.php(266): Adldap\\Adldap->Adldap\\{closure}('Adldap\\\\Auth\\\\Eve...', Array)
#12 /home/warlord/itsm/vendor/adldap2/adldap2/src/Events/Dispatcher.php(112): Adldap\\Events\\Dispatcher->Adldap\\Events\\{closure}('Adldap\\\\Auth\\\\Eve...', Array)
#13 /home/warlord/itsm/vendor/adldap2/adldap2/src/Events/Dispatcher.php(94): Adldap\\Events\\Dispatcher->dispatch('Adldap\\\\Auth\\\\Eve...', Array, false)
#14 /home/warlord/itsm/vendor/adldap2/adldap2/src/Auth/Guard.php(243): Adldap\\Events\\Dispatcher->fire(Object(Adldap\\Auth\\Events\\Binding))
#15 /home/warlord/itsm/vendor/adldap2/adldap2/src/Auth/Guard.php(98): Adldap\\Auth\\Guard->fireBindingEvent('warlord@charnw...', '******')
#16 /home/warlord/itsm/vendor/adldap2/adldap2/src/Auth/Guard.php(121): Adldap\\Auth\\Guard->bind('warlord@charnw...', '******')
#17 /home/warlord/itsm/vendor/adldap2/adldap2/src/Connections/Provider.php(234): Adldap\\Auth\\Guard->bindAsAdministrator()
#18 /home/warlord/itsm/vendor/adldap2/adldap2-laravel/src/AdldapServiceProvider.php(111): Adldap\\Connections\\Provider->connect()
#19 /home/warlord/itsm/vendor/adldap2/adldap2-laravel/src/AdldapServiceProvider.php(68): Adldap\\Laravel\\AdldapServiceProvider->addProviders(Object(Adldap\\Adldap), Array)
#20 /home/warlord/itsm/vendor/laravel/framework/src/Illuminate/Container/Container.php(787): Adldap\\Laravel\\AdldapServiceProvider->Adldap\\Laravel\\{closure}(Object(Illuminate\\Foundation\\Application), Array)
#21 /home/warlord/itsm/vendor/laravel/framework/src/Illuminate/Container/Container.php(667): Illuminate\\Container\\Container->build(Object(Closure))
#22 /home/warlord/itsm/vendor/laravel/framework/src/Illuminate/Container/Container.php(615): Illuminate\\Container\\Container->resolve('Adldap\\\\AdldapIn...', Array)
#23 /home/warlord/itsm/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(767): Illuminate\\Container\\Container->make('Adldap\\\\AdldapIn...', Array)
#24 /home/warlord/itsm/vendor/adldap2/adldap2-laravel/src/AdldapAuthServiceProvider.php(55): Illuminate\\Foundation\\Application->make('Adldap\\\\AdldapIn...')
#25 /home/warlord/itsm/vendor/laravel/framework/src/Illuminate/Container/Container.php(787): Adldap\\Laravel\\AdldapAuthServiceProvider->Adldap\\Laravel\\{closure}(Object(Illuminate\\Foundation\\Application), Array)
#26 /home/warlord/itsm/vendor/laravel/framework/src/Illuminate/Container/Container.php(667): Illuminate\\Container\\Container->build(Object(Closure))
#27 /home/warlord/itsm/vendor/laravel/framework/src/Illuminate/Container/Container.php(615): Illuminate\\Container\\Container->resolve('Adldap\\\\Laravel\\\\...', Array)
#28 /home/warlord/itsm/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(767): Illuminate\\Container\\Container->make('Adldap\\\\Laravel\\\\...', Array)
#29 /home/warlord/itsm/vendor/laravel/framework/src/Illuminate/Container/Container.php(1229): Illuminate\\Foundation\\Application->make('Adldap\\\\Laravel\\\\...')
#30 /home/warlord/itsm/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(175): Illuminate\\Container\\Container->offsetGet('Adldap\\\\Laravel\\\\...')
#31 /home/warlord/itsm/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(144): Illuminate\\Support\\Facades\\Facade::resolveFacadeInstance('Adldap\\\\Laravel\\\\...')
#32 /home/warlord/itsm/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(231): Illuminate\\Support\\Facades\\Facade::getFacadeRoot()
#33 /home/warlord/itsm/vendor/adldap2/adldap2-laravel/src/Listeners/BindsLdapUserModel.php(33): Illuminate\\Support\\Facades\\Facade::__callStatic('byModel', Array)
#34 [internal function]: Adldap\\Laravel\\Listeners\\BindsLdapUserModel->handle(Object(Illuminate\\Auth\\Events\\Authenticated))
#35 /home/warlord/itsm/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(366): call_user_func_array(Array, Array)
#36 /home/warlord/itsm/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(196): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}('Illuminate\\\\Auth...', Array)
#37 /home/warlord/itsm/vendor/laravel/framework/src/Illuminate/Auth/SessionGuard.php(618): Illuminate\\Events\\Dispatcher->dispatch('Illuminate\\\\Auth...')
#38 /home/warlord/itsm/vendor/laravel/framework/src/Illuminate/Auth/SessionGuard.php(774): Illuminate\\Auth\\SessionGuard->fireAuthenticatedEvent(Object(App\\User))
#39 /home/warlord/itsm/vendor/laravel/framework/src/Illuminate/Auth/SessionGuard.php(235): Illuminate\\Auth\\SessionGuard->setUser(Object(App\\User))
#40 /home/warlord/itsm/vendor/tymon/jwt-auth/src/Providers/Auth/Illuminate.php(59): Illuminate\\Auth\\SessionGuard->onceUsingId(9696)
#41 /home/warlord/itsm/vendor/tymon/jwt-auth/src/JWTAuth.php(66): Tymon\\JWTAuth\\Providers\\Auth\\Illuminate->byId(9696)
#42 /home/warlord/itsm/vendor/tymon/jwt-auth/src/Http/Middleware/BaseMiddleware.php(70): Tymon\\JWTAuth\\JWTAuth->authenticate()
#43 /home/warlord/itsm/vendor/tymon/jwt-auth/src/Http/Middleware/Authenticate.php(30): Tymon\\JWTAuth\\Http\\Middleware\\BaseMiddleware->authenticate(Object(Illuminate\\Http\\Request))
#44 /home/warlord/itsm/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Tymon\\JWTAuth\\Http\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#45 /home/warlord/itsm/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#46 /home/warlord/itsm/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#47 /home/warlord/itsm/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#48 /home/warlord/itsm/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#49 /home/warlord/itsm/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(58): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#50 /home/warlord/itsm/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Routing\\Middleware\\ThrottleRequests->handle(Object(Illuminate\\Http\\Request), Object(Closure), 60, '1')
#51 /home/warlord/itsm/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#52 /home/warlord/itsm/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#53 /home/warlord/itsm/vendor/laravel/framework/src/Illuminate/Routing/Router.php(682): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#54 /home/warlord/itsm/vendor/laravel/framework/src/Illuminate/Routing/Router.php(657): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#55 /home/warlord/itsm/vendor/laravel/framework/src/Illuminate/Routing/Router.php(623): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#56 /home/warlord/itsm/vendor/laravel/framework/src/Illuminate/Routing/Router.php(612): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#57 /home/warlord/itsm/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#58 /home/warlord/itsm/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#59 /home/warlord/itsm/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#60 /home/warlord/itsm/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#61 /home/warlord/itsm/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#62 /home/warlord/itsm/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#63 /home/warlord/itsm/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#64 /home/warlord/itsm/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#65 /home/warlord/itsm/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#66 /home/warlord/itsm/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#67 /home/warlord/itsm/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#68 /home/warlord/itsm/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#69 /home/warlord/itsm/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#70 /home/warlord/itsm/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#71 /home/warlord/itsm/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#72 /home/warlord/itsm/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#73 /home/warlord/itsm/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#74 /home/warlord/itsm/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#75 /home/warlord/itsm/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#76 /home/warlord/itsm/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#77 /home/warlord/itsm/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php(375): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#78 /home/warlord/itsm/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php(197): Illuminate\\Foundation\\Testing\\TestCase->call('POST', '/api/foi/delega...', Array, Array, Array, Array)
#79 /home/warlord/itsm/tests/Unit/FOI/FOIDelegatedQuestionsTest.php(153): Illuminate\\Foundation\\Testing\\TestCase->post('/api/foi/delega...', Array)
#80 /home/warlord/itsm/vendor/phpunit/phpunit/src/Framework/TestCase.php(1154): Tests\\Unit\\FOIDelegatedQuestionsTest->testApiReinstateDelegation()
#81 /home/warlord/itsm/vendor/phpunit/phpunit/src/Framework/TestCase.php(842): PHPUnit\\Framework\\TestCase->runTest()
#82 /home/warlord/itsm/vendor/phpunit/phpunit/src/Framework/TestResult.php(693): PHPUnit\\Framework\\TestCase->runBare()
#83 /home/warlord/itsm/vendor/phpunit/phpunit/src/Framework/TestCase.php(796): PHPUnit\\Framework\\TestResult->run(Object(Tests\\Unit\\FOIDelegatedQuestionsTest))
#84 /home/warlord/itsm/vendor/phpunit/phpunit/src/Framework/TestSuite.php(746): PHPUnit\\Framework\\TestCase->run(Object(PHPUnit\\Framework\\TestResult))
#85 /home/warlord/itsm/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(652): PHPUnit\\Framework\\TestSuite->run(Object(PHPUnit\\Framework\\TestResult))
#86 /home/warlord/itsm/vendor/phpunit/phpunit/src/TextUI/Command.php(206): PHPUnit\\TextUI\\TestRunner->doRun(Object(PHPUnit\\Framework\\TestSuite), Array, true)
#87 /home/warlord/itsm/vendor/phpunit/phpunit/src/TextUI/Command.php(162): PHPUnit\\TextUI\\Command->run(Array, true)
#88 /home/warlord/itsm/vendor/phpunit/phpunit/phpunit(61): PHPUnit\\TextUI\\Command::main()
#89 {main}
"} 
```

**Comment by stevebauman** [comment]
Hi @warlord0,

This seems like it's an issue with how your test environment is spinning up since the Laravel container is saying `config` doesn't exist.

Can you post your base `TestCase` class and a couple test cases that fail?

**Comment by tsterker** [comment]
@warlord0 did you happen to identify the issue? I'm also struggling with the same error in a similar context and none of the other suggestions I stumbled upon so far seem to really help.

My current workaround is to either
**a)** only have a single test method in the test case
**b)** have the "offending" unit test overwrite `tearDown` and not call `parent::tearDown` (ouch?)  
  *(` $this->app->flush();` in `Illuminate\Foundation\Testing\TestCase` seems to be the culprit here)*
